apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aat14-eks-cluster
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 100
    ssh:
      allow: false
      #publicKeyPath: ~/.ssh/ec2_id_rsa.pub