apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aat14-eks-sandbox-cluster
  region: eu-west-1

vpc:
  id: "vpc-111111"  
  subnets:
    private:
      eu-west-1a: { id: subnet-111111 }
      eu-west-1b: { id: subnet-222222 }

nodeGroups:
  - name: aat14-ng-1-workers
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    labels: { role: workers }
    instanceType: t3.medium
    volumeSize: 50
    privateNetworking: true
  - name: aat14-ng-2-builders
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    labels: { role: builders }
    instanceType: t3.medium
    volumeSize: 50
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true